apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "5"
        memory: "5Gi"
      limits:
        cpu: "5"
        memory: "5Gi"
  restartPolicy: Never